name: checks
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - shell: pwsh
        run: |
          Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck
          Install-Module DataAgent -RequiredVersion 0.5.0 -Scope CurrentUser -Force
          Install-Module PilotCarrierClient -RequiredVersion 1.0.0 -Scope CurrentUser -Force
          Install-Module Add-PrefixForLogging, Clear-Files, SqlServer -Scope CurrentUser -Force -AcceptLicense
          Test-ModuleManifest ./PilotCarrierIntegration/PilotCarrierIntegration.psd1 | Out-Null
          Invoke-Pester ./tests -CI
